apiVersion: v1
kind: Service
metadata:
  name: mimis-shop
spec:
  selector:
    app: mimis-shop # Should match what you have in template.metadata.labels of your Deployment resource
  ports:
    - port: 8000
      targetPort: 9099
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimis-shop
spec: # Pod Definition
  replicas: 1
  selector:
    matchLabels:
      app: mimis-shop
  template:
    metadata:
      labels:
        app: mimis-shop
    spec:
      containers:
        - name: mimis-shop
          image: jiobiagba/demo-shopping-app-be
          ports:
            - containerPort: 9099
          imagePullPolicy: Always
